name: Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install linters
        run: npm install -g eslint-plugin-yml eslint-config-standard

      - name: Run linters
        run: eslint --ext .yml .
